---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12

platforms:
  - name: centos-7.1
  - name: centos-6

suites:
  - name: default
    run_list:
      - recipe[training-cookbook::install_packages]
      - recipe[supervisor::default]
      - recipe[training-cookbook::default]
    excludes:
      - centos-6
    attributes:
  - name: centos6
    run_list:
      - recipe[training-cookbook::install_packages]
      - recipe[supervisor::compile_python]
      - recipe[supervisor::default]
      - recipe[training-cookbook::default]
    excludes:
      - centos-7.1
    attributes:
