---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[supervisor::default]
      - recipe[training-cookbook::default]
    attributes:
